Add fixes to build agl-image-minimal successfully
1. The extra/files/group and extra/files/passwd files are added
with "test" username and groupname, in order to solve below error
when ptest is enabled.

-- snip --
ERROR: Nothing RPROVIDES 'bash' (but .../layers/poky/meta/recipes-devtools/tcf-agent/tcf-agent_git.bb, .../layers/poky/meta/recipes-devtools/rpm/rpm_git.bb, .../layers/poky/meta/recipes-core/systemd/systemd_234.bb, .../layers/meta-agl/meta-agl-profile-core/recipes-test/afb-test/afb-test_git.bb, .../layers/poky/meta/recipes-kernel/perf/perf.bb, .../layers/poky/meta/recipes-support/bash-completion/bash-completion_2.7.bb, .../layers/meta-agl/meta-agl-profile-core/recipes-connectivity/neardal/neardal_0.14.bb, .../layers/poky/meta/recipes-core/dbus/dbus-test_1.10.20.bb RDEPENDS on or otherwise requires it)
bash was skipped: bash - bash-ptest: normal username test does not have a static ID defined. Add test to one of these files: .../layers/meta-agl/meta-agl-profile-core/files/passwd
-- snip --

2. swig-native is added as dependency to solve below error:
-- snip --
| swig -o audit_wrap.c -python -I. -I.. -I../../audit-2.3.2/lib -I.../tmp/work/cortexa7hf-neon-vfpv4-montavista-linux-gnueabi/audit/2.3.2-r8/recipe-sysroot/usr/include/python2.7 -I.../tmp/work/cortexa7hf-neon-vfpv4-montavista-linux-gnueabi/audit/2.3.2-r8/recipe-sysroot/usr/include ../../audit-2.3.2/swig/auditswig.i
| make[2]: swig: Command not found
| make[2]: *** [Makefile:749: audit_wrap.c] Error 127
-- snip --

3. Do not execute sed command in do_install_class-native as
   "${STAGING_DIR_HOST}" is empty,
-- snip --
sed: -e expression #1, char 0: no previous regular expression
WARNING: .../tmp/work/x86_64-linux/xmlsec1-native/1.2.24-r0/temp/run.do_install.22057:1 exit 1 from 'sed -i -e "s@@@g" .tmp/work/x86_64-linux/xmlsec1-native/1.2.24-r0/image.tmp/work/x86_64-linux/xmlsec1-native/1.2.24-r0/recipe-sysroot-native/usr/bin/xmlsec1-config'
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>